config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  get '/admin', to: 'posts#admin'
  get '/cart', to: 'cart#show'
  delete 'logout', to: 'posts#logout_admin', as: :logout

  post 'cart/add_item', to: 'cart#add_item', as: 'add_item_cart'
  post 'cart/clear', to: 'cart#clear_cart', as: 'clear_cart'

  delete 'remove_item_cart/:id', to: 'cart#remove_item', as: 'remove_item_cart'

  root "posts#index", as: 'home'
  
  get "about" => "pages#about", as: 'about'

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :post
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  has_many :comments, dependent: :destroy
  has_many :cart_items
  validates :title, presence: true, length: {minimum: 5} 
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @cart_items = CartItem.all
  end

  def add_item
    @post = Post.find(params[:post_id])
    @cart_item = CartItem.new(post: @post, quantity: 1) 
    if @cart_item.save
      if params[:redirect_to_cart]
        redirect_to cart_path, notice: "Товар додано до кошика. Перенаправлення до кошика..."
      else
        redirect_to @post, notice: "Товар додано до кошика!"
      end
    else
      redirect_to @post, alert: "Не вдалося додати товар до кошика."
    end
  end

  def clear_cart
    @cart_items = CartItem.all
    @cart_items.each(&:destroy)
    redirect_to cart_path, notice: "Ваше замовлення оформлене!"
  end
  
  def remove_item
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_path, alert: "Товар видалено з кошика."
  end

  private

  def item_params
    params.require(:cart_item).permit(:product_id, :quantity)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post), notice: 'Коментар видалено.'
  end

  private def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @heading = "Вітаємо у RemBud!"
    @text = "Ласкаво просимо до Rembud – вашого надійного партнера у світі будівельних матеріалів в Івано-Франківську!
     Наша компанія спеціалізується на продажу високоякісних будівельних сумішей, які відповідають найвищим стандартам якості 
     та допомагають забезпечити тривалість і надійність ваших проектів. Ми пропонуємо широкий асортимент товарів для різних 
     етапів будівництва та ремонту, серед яких клеї для плитки, штукатурки, стяжки та інші суміші, що
      зроблять процес будівництва легшим та ефективнішим.У Rembud ми віримо, що успіх будівельного проекту
       починається з якісних матеріалів та професійної підтримки. Наша команда завжди готова надати консультації та допомогу
        у виборі необхідної продукції, щоб ви могли втілити в життя свої ідеї без зайвих труднощів.
         Обираючи нас, ви обираєте якість, надійність та професіоналізм. Дякуємо, що обрали Rembud!"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]

  def admin
    session[:admin] = true
    redirect_to posts_path, notice: "Ви увійшли як адміністратор"
  end

  def logout_admin
    reset_session
    redirect_to posts_path, alert: "Ви вийшли з ролі адміністратора"
  end

  def index
    @posts = Post.all
  end

  def new
      @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if (@post.update(post_params))
      redirect_to @post, notice: "Публікацію оновлено успішно."
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])

    @post.destroy

    redirect_to posts_path, alert: "Публікацію видалено."
  end

  def create
    @post = Post.new(post_params)

    if (@post.save)
      redirect_to @post, notice: "Публікацію створено успішно."
    else
      render :new
    end
  end

  private def post_params
    params.require(:post).permit(:title, :price, :body, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/cart/show.html.erb
<h2>Ваш кошик</h2>
<% if @cart_items.any? %>
  <% total_sum = 0 %>
  <div class="row">
    <% @cart_items.each do |item| %>
      <% total_sum += item.post.price * item.quantity %>
      <div class="col-md-4 mb-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= item.post.title %></h5>
            <p class="card-text">Кількість: <%= item.quantity %> шт.</p>
            <p class="card-text">Ціна: <%= number_with_precision(item.post.price * item.quantity, precision: 2) %> ₴</p>
            <%= button_to "Видалити", remove_item_cart_path(item.id), method: :delete, class: "btn btn-danger" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  
  <h3 style="text-align:center">Загальна сума: <%= number_with_precision(total_sum, precision: 2) %> ₴</h3>
  
  <h3>Оформлення замовлення</h3>
  <%= form_with url: clear_cart_path, method: :post do %>
    <div class="mb-3">
      <label for="full_name" class="form-label">ПІБ</label>
      <input type="text" class="form-control" id="full_name" name="full_name" required>
    </div>
    <div class="mb-3">
      <label for="phone_number" class="form-label">Номер телефону</label>
      <input type="tel" class="form-control" id="phone_number" name="phone_number" required>
    </div>
    <div class="mb-3">
      <label for="address" class="form-label">Адреса доставки</label>
      <input type="text" class="form-control" id="address" name="address" required>
    </div>
    <div class="mb-3">
      <label for="comment" class="form-label">Коментар</label>
      <textarea class="form-control" id="comment" name="comment"></textarea>
    </div>
    <div class="mb-3">
      <label for="payment_type" class="form-label">Тип оплати</label>
      <select class="form-select" id="payment_type" name="payment_type" required>
        <option value="">Оберіть тип оплати</option>
        <option value="credit_card">Кредитна картка</option>
        <option value="paypal">PayPal</option>
        <option value="cash_on_delivery">Готівкою при отриманні</option>
      </select>
    </div>
    <div class="text-center">
      <%= button_tag "Замовити", type: :submit, class: "btn btn-success"%>
    </div>
  <% end %>
<% else %>
  <p>Ваш кошик порожній.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
      <title><%= content_for(:title) || "Store" %></title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <meta name="apple-mobile-web-app-capable" content="yes">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= yield :head %>
      <link rel="manifest" href="/manifest.json">
      <link rel="icon" href="/icon.png" type="image/png">
      <link rel="icon" href="/icon.svg" type="image/svg+xml">
      <link rel="apple-touch-icon" href="/icon.png">
      <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"%>
      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
      <%= javascript_importmap_tags %>
   </head>
   <body class="bg-light text-dark d-flex flex-column min-vh-100">
      <% if flash[:notice] %>
         <div class="alert alert-success">
            <%= flash[:notice] %>
         </div>
      <% end %>

      <% if flash[:alert] %>
         <div class="alert alert-danger">
            <%= flash[:alert] %>
         </div>
      <% end %>
      <header style="padding:25px">
         <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
            <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
               <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img">
                  <title>Rembud</title>
                  <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path>
               </svg>
               <span class="fs-4">Rembud</span>
            </a>
            <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
               <span class="me-3 py-2 link-body-emphasis text-decoration-none links"><%= link_to "Головна сторінка", home_path %></span>
               <span class="me-3 py-2 link-body-emphasis text-decoration-none links"><%= link_to "Про нас", about_path %></span>
               <% if session[:admin] %>
               <span class="me-3 py-2 link-body-emphasis text-decoration-none links">
               <%= link_to "Додати товар", new_post_path %>
               </span>
               <% else %>
               <span class="me-3 py-2 link-body-emphasis text-decoration-none links">
               <%= link_to "Кошик", cart_path %>
               </span>
               <% end %>
            </nav>
         </div>
      </header>
      <div class="container">
         <%= yield %>
      </div>
      <footer class="d-flex flex-wrap justify-content-between align-items-center my-4 border-top">
         <p class="col-md-4 mb-0 text-body-secondary">© 2024 Rembud Company, Inc</p>
         <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img">
               <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path>
            </svg>
         </a>
         <ul class="nav col-md-4 justify-content-end">
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">+380981882200</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">+380501882220</a></li>
            <li class="nav-item"><a href="https://github.com/ArsenHavadzyn" class="nav-link px-2 text-body-secondary">Github</a></li>
            <li class="nav-item"><a href="https://www.linkedin.com/in/arsen-gavadzyn-1546041bb/" class="nav-link px-2 text-body-secondary">LinkedIn</a></li>
            <% if session[:admin] %><li class="nav-item"><%= button_to "Вихід", logout_path, method: :delete, data: { confirm: "Ви впевнені, що хочете вийти?" }, :class => "nav-link px-2 text-body-secondary" %></a></li><% end %>
         </ul>
      </footer>
   </body>
</html>

app/views/pages/about.html.erb
<div class="about-container">
    <h1><%= @heading %></h1>
    <hr>
    <img class="about-img" src="https://www.companysetup.ae/wp-content/uploads/2023/11/Start-a-Building-Materials-Trading-Company-in-Dubai-1200x675.jpg">
    <p><%= @text %></p>
</div>

app/views/posts/edit.html.erb
<h2>Редагування публікації №<%= @post.id %></h2>
<%= form_for :post, url: post_path(@post), method: :patch, html: { multipart: true, data: { turbo: false } } do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
    <p>
        Назва
        <br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>
    <p>
        Ціна
        <br>
        <%= f.number_field :price, step: 0.01, class: 'form-control' %>
</p>
    <p>
        Опис
        <br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
    <p>
        Фотографія
        <br>
        <%= f.file_field :image, class: 'form-control' %>
    </p>
    <p>
        <%= f.submit({:class => 'btn btn-success'}) %>
    </p>
    
<% end %>

app/views/posts/index.html.erb
<h1 style="text-align:center;">Наші товари</h1>
<hr>
<br>
<div class="posts-container">
  <% @posts.each do |post| %>
    <div class="post-card alert alert-light">
      <h4 class="post-title"><%= post.title %></h4>
      <div class="image-wrapper">
        <% if post.image.attached? %>
          <%= image_tag post.image, class: 'img-thumbnail', alt: 'Мініатюра' %>
        <% end %>
      </div>
      <p class="post-price"><%= number_with_precision(post.price, precision: 2) %> ₴</p>
      <%= link_to "Детальніше..", post_path(post), class: "btn btn-outline-primary post-details-button" %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h2>Додавання нового товару</h2>

<%= form_for @post, url: posts_path, html: { multipart: true, data: { turbo: false } } do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
    
    <p>
        Назва
        <br>
        <%= f.text_field(:title, class: 'form-control') %>
    </p>
    <p>
        Ціна
        <br>
        <%= f.number_field :price, step: 0.01, class: 'form-control' %>
    </p>
    <p>
        Опис
        <br>
        <%= f.text_area(:body, class: 'form-control') %>
    </p>
    
    <p>
        Фотографія
        <br>
        <%= f.file_field :image, class: 'form-control' %>
    </p>
    
    <p>
        <%= f.submit "Зберегти", class: 'btn btn-success' %>
    </p>
<% end %>

app/views/posts/show.html.erb
<h1 class="text-center"><%= @post.title %></h1>

<br>
<div class="row">
  <% if @post.image.attached? %>
    <div class="col-md-6 imgcol">
      <%= image_tag @post.image, class: 'img-fluid', alt: 'Зображення публікації' %>
    </div>
  <% end %>
  <div class="col-md-6">
    <h3 style="text-align:center; padding-bottom:5px;">Опис товару:</h3>
    <%= simple_format(@post.body) if @post.body.present? %>
    <h4 class="h4-price">Ціна: <%= number_with_precision(@post.price, precision: 2) %> ₴</h4>
    <hr>
  </div>
</div>
<% if session[:admin] %>
  <div class="button-group d-flex align-items-center justify-content-center">
   <%= link_to "Редагувати", edit_post_path(@post), class: "btn btn-warning" %>
   <%= button_to "Видалити", post_path(@post), method: :delete, data: {turbo_method: :delete, turbo_confirm: 'Ви впевнені?'}, class: "btn btn-danger" %>
  </div>
<% else %>
  <div class="button-group d-flex align-items-center justify-content-center">
  <%= button_to "Додати до кошика", add_item_cart_path(post_id: @post.id), method: :post, class: "btn btn-primary" %>
  <%= button_to "Придбати", add_item_cart_path(post_id: @post.id), method: :post, params: { redirect_to_cart: true }, class: "btn btn-success" %>
  </div>  
<% end %>

<hr>
<h2>Усі коментарі</h2>
<br>
<% @post.comments.each do |comment| %>
  <div class="alert alert-light comment-container">
    <p><strong><%= comment.username %></strong>: <%= comment.body %></p>
    <% if session[:admin] %>
      <%= form_with model: [@post, comment], method: :delete, local: true do %>
        <button type="submit" class="close-button" data-confirm="Ви впевнені, що хочете видалити цей коментар?">✖</button>
      <% end %>
    <% end %>
  </div>
<% end %>




<% if !session[:admin] %>
<hr>
<h2>Залишити відгук</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
        Користувач
        <br>
        <%= f.text_field(:username, class: 'form-control') %>
    </p>
    <p>
        Текст коментаря
        <br>
        <%= f.text_area(:body, class: 'form-control') %>
    </p>

    <p>
        <%= f.submit("Опублікувати", class: 'btn btn-warning') %>
    </p>
<% end %>
<% end %>